grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 1
    n_jobs: -1

model_selection:
  module_0:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [200]
    #   max_depth: [7, 8]
    #   min_samples_split: [7, 10]
    #   min_samples_leaf: [3, 5]

  module_1:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      learning_rate: [0.01, 0.05]
    #   n_estimators: [200, 250]
    #   max_depth: [5, 7]
    #   subsample: [0.7, 0.8]

  module_2:
    class: XGBClassifier
    module: xgboost
    params:
      objective: binary:logistic
      eval_metric: logloss
      random_state: 42
      use_label_encoder: False
    search_param_grid:
      n_estimators: [200,250]
      # n_estimators: [168,170]
    #   max_depth: [5, 7]
    #   learning_rate: [0.04, 0.05]
    #   subsample: [0.7, 0.8]
    #   colsample_bytree: [0.6, 0.8]
      # early_stopping_rounds: [30,50]

  # Optional: Add more models here
  # module_3:
  #   class: LogisticRegression
  #   module: sklearn.linear_model
  #   params:
  #     random_state: 42
  #   search_param_grid:
  #     C: [0.1, 1.0, 10.0]
  #     penalty: ["l2"]
  #     solver: ["lbfgs", "liblinear"]
